/* LangParser.java */
/* Generated By:JavaCC: Do not edit this line. LangParser.java */
package org.tec.comp.interpreter;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.ArrayList;

public class LangParser implements TestConstants {

    private ArrayList<String> msg_list = new ArrayList<>();

    /*public static void main(String[] args) throws ParseException {
        try{
            LangParser analyser = new LangParser(System.in);
            analyser.Program();
            System.out.println("Successful compilation");
        } catch(ParseException pe) {
            System.out.println(pe.getMessage());
            System.out.println("ERRORS");
        }
    }*/

    static public void parse(String file) throws ParseException {
        try{
            LangParser analyser = new LangParser(new BufferedReader(new FileReader(file)));
            analyser.Program();
            System.out.println("Successful compilation");
        } catch(ParseException pe) {
            System.out.println(pe.getMessage());
            System.out.println("ERRORS");
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
    }

  static final public void Program() throws ParseException {
    IdField();
    Main();
    Procedures();
    jj_consume_token(0);
  }

  static final public void Main() throws ParseException {
    jj_consume_token(BEGIN);
    jj_consume_token(LBRACKET);
    Expressions();
    jj_consume_token(RBRACKET);
    jj_consume_token(END);
  }

  static final public void VarDeclaration() throws ParseException {
    jj_consume_token(VARIABLE);
    jj_consume_token(IDENTIFIER);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case SEMICOLON:{
      jj_consume_token(SEMICOLON);
      break;
      }
    case EQUAL:{
      jj_consume_token(EQUAL);
      jj_consume_token(INTEGER);
      jj_consume_token(SEMICOLON);
      break;
      }
    default:
      jj_la1[0] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void VarSet() throws ParseException {
    jj_consume_token(SET);
    jj_consume_token(IDENTIFIER);
    jj_consume_token(EQUAL);
    jj_consume_token(INTEGER);
    jj_consume_token(SEMICOLON);
  }

  static final public void VarIncrement() throws ParseException {
    jj_consume_token(INCREMENT);
    jj_consume_token(IDENTIFIER);
    jj_consume_token(SEMICOLON);
  }

  static final public void VarDecrement() throws ParseException {
    jj_consume_token(DECREMENT);
    jj_consume_token(IDENTIFIER);
    jj_consume_token(SEMICOLON);
  }

  static final public void PlaceBlock() throws ParseException {
    jj_consume_token(PLACEBLOCK);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INTEGER:{
      jj_consume_token(INTEGER);
      jj_consume_token(SEMICOLON);
      break;
      }
    case SEMICOLON:{
      jj_consume_token(SEMICOLON);
      break;
      }
    default:
      jj_la1[1] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void HighBlock() throws ParseException {
    jj_consume_token(HIGHBLOCK);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INTEGER:{
      jj_consume_token(INTEGER);
      jj_consume_token(SEMICOLON);
      break;
      }
    case SEMICOLON:{
      jj_consume_token(SEMICOLON);
      break;
      }
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void PosFunc() throws ParseException {
    jj_consume_token(POSFUNC);
    jj_consume_token(LBRACKET);
    jj_consume_token(IDENTIFIER);
    jj_consume_token(COMMA);
    jj_consume_token(IDENTIFIER);
    jj_consume_token(RBRACKET);
    jj_consume_token(SEMICOLON);
  }

  static final public void PutLight() throws ParseException {
    jj_consume_token(PUTLIGHT);
    jj_consume_token(SEMICOLON);
  }

  static final public void KeepStatement() throws ParseException {
    jj_consume_token(KEEP);
    Expressions();
    jj_consume_token(SKP);
    jj_consume_token(KEND);
    jj_consume_token(SEMICOLON);
  }

  static final public void ForStatement() throws ParseException {
    jj_consume_token(FOR);
    jj_consume_token(IDENTIFIER);
    jj_consume_token(EQUAL);
    jj_consume_token(INTEGER);
    jj_consume_token(TIMES);
    Expressions();
    jj_consume_token(FEND);
    jj_consume_token(SEMICOLON);
  }

  static final public void WhenStatement() throws ParseException {
    jj_consume_token(WHEN);
    jj_consume_token(IDENTIFIER);
    jj_consume_token(EQUAL);
    jj_consume_token(INTEGER);
    jj_consume_token(THEN);
    Expressions();
    jj_consume_token(WHEND);
    jj_consume_token(SEMICOLON);
  }

  static final public void PosStartFunc() throws ParseException {
    jj_consume_token(POSSTARTFUNC);
    jj_consume_token(LBRACKET);
    jj_consume_token(IDENTIFIER);
    jj_consume_token(COMMA);
    jj_consume_token(IDENTIFIER);
    jj_consume_token(RBRACKET);
    jj_consume_token(SEMICOLON);
  }

  static final public void CallProc() throws ParseException {
    jj_consume_token(CALL);
    jj_consume_token(PROCNAME);
    jj_consume_token(SEMICOLON);
  }

  static final public void ChangeDirFunc() throws ParseException {
    jj_consume_token(CHANGEDIR);
    jj_consume_token(LBRACKET);
    jj_consume_token(SLBRACKET);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LEFT:{
      jj_consume_token(LEFT);
      break;
      }
    case RIGHT:{
      jj_consume_token(RIGHT);
      break;
      }
    case BACK:{
      jj_consume_token(BACK);
      break;
      }
    case SAME:{
      jj_consume_token(SAME);
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(SRBRACKET);
    jj_consume_token(RBRACKET);
    jj_consume_token(SEMICOLON);
  }

  static final public void IdField() throws ParseException {
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case VARIABLE:{
        ;
        break;
        }
      default:
        jj_la1[4] = jj_gen;
        break label_1;
      }
      VarDeclaration();
    }
  }

  static final public void Procedures() throws ParseException {
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PROC:{
        ;
        break;
        }
      default:
        jj_la1[5] = jj_gen;
        break label_2;
      }
      jj_consume_token(PROC);
      jj_consume_token(PROCNAME);
      Expressions();
      jj_consume_token(ENDPROC);
    }
  }

  static final public void Expressions() throws ParseException {
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case VARIABLE:
      case SET:
      case INCREMENT:
      case DECREMENT:
      case PLACEBLOCK:
      case HIGHBLOCK:
      case POSFUNC:
      case PUTLIGHT:
      case KEEP:
      case FOR:
      case WHEN:
      case POSSTARTFUNC:
      case CALL:
      case CHANGEDIR:{
        ;
        break;
        }
      default:
        jj_la1[6] = jj_gen;
        break label_3;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case VARIABLE:{
        VarDeclaration();
        break;
        }
      case SET:{
        VarSet();
        break;
        }
      case INCREMENT:{
        VarIncrement();
        break;
        }
      case DECREMENT:{
        VarDecrement();
        break;
        }
      case PLACEBLOCK:{
        PlaceBlock();
        break;
        }
      case HIGHBLOCK:{
        HighBlock();
        break;
        }
      case POSFUNC:{
        PosFunc();
        break;
        }
      case PUTLIGHT:{
        PutLight();
        break;
        }
      case KEEP:{
        KeepStatement();
        break;
        }
      case FOR:{
        ForStatement();
        break;
        }
      case WHEN:{
        WhenStatement();
        break;
        }
      case POSSTARTFUNC:{
        PosStartFunc();
        break;
        }
      case CALL:{
        CallProc();
        break;
        }
      case CHANGEDIR:{
        ChangeDirFunc();
        break;
        }
      default:
        jj_la1[7] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public TestTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[8];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x600,0x400,0x400,0x0,0x1000,0x40000,0x51f0f000,0x51f0f000,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0x100,0x100,0xf0,0x0,0x0,0xe,0xe,};
   }

  /** Constructor with InputStream. */
  public LangParser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public LangParser(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new TestTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 8; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 8; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public LangParser(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new TestTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 8; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 8; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public LangParser(TestTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 8; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(TestTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 8; i++) jj_la1[i] = -1;
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk_f() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[46];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 8; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 46; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

}
