package org.tec.comp.interpreter;/* Generated By:JavaCC: Do not edit this line. TestConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TestConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 1;
  /** RegularExpression Id. */
  int PROGRAM = 2;
  /** RegularExpression Id. */
  int LBRACKET = 3;
  /** RegularExpression Id. */
  int RBRACKET = 4;
  /** RegularExpression Id. */
  int SLBRACKET = 5;
  /** RegularExpression Id. */
  int SRBRACKET = 6;
  /** RegularExpression Id. */
  int CLBRACKET = 7;
  /** RegularExpression Id. */
  int CRBRACKET = 8;
  /** RegularExpression Id. */
  int EQUAL = 9;
  /** RegularExpression Id. */
  int SEMICOLON = 10;
  /** RegularExpression Id. */
  int COMMA = 11;
  /** RegularExpression Id. */
  int VARIABLE = 12;
  /** RegularExpression Id. */
  int SET = 13;
  /** RegularExpression Id. */
  int INCREMENT = 14;
  /** RegularExpression Id. */
  int DECREMENT = 15;
  /** RegularExpression Id. */
  int BEGIN = 16;
  /** RegularExpression Id. */
  int END = 17;
  /** RegularExpression Id. */
  int PROC = 18;
  /** RegularExpression Id. */
  int ENDPROC = 19;
  /** RegularExpression Id. */
  int PLACEBLOCK = 20;
  /** RegularExpression Id. */
  int HIGHBLOCK = 21;
  /** RegularExpression Id. */
  int POSFUNC = 22;
  /** RegularExpression Id. */
  int PUTLIGHT = 23;
  /** RegularExpression Id. */
  int KEEP = 24;
  /** RegularExpression Id. */
  int KEND = 25;
  /** RegularExpression Id. */
  int TIMES = 26;
  /** RegularExpression Id. */
  int SKP = 27;
  /** RegularExpression Id. */
  int FOR = 28;
  /** RegularExpression Id. */
  int FEND = 29;
  /** RegularExpression Id. */
  int WHEN = 30;
  /** RegularExpression Id. */
  int WHEND = 31;
  /** RegularExpression Id. */
  int THEN = 32;
  /** RegularExpression Id. */
  int POSSTARTFUNC = 33;
  /** RegularExpression Id. */
  int CALL = 34;
  /** RegularExpression Id. */
  int CHANGEDIR = 35;
  /** RegularExpression Id. */
  int RIGHT = 36;
  /** RegularExpression Id. */
  int LEFT = 37;
  /** RegularExpression Id. */
  int BACK = 38;
  /** RegularExpression Id. */
  int SAME = 39;
  /** RegularExpression Id. */
  int INTEGER = 40;
  /** RegularExpression Id. */
  int PROCNAME = 41;
  /** RegularExpression Id. */
  int IDENTIFIER = 42;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"public static void Main()\"",
    "\"Program\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\";\"",
    "\",\"",
    "\"Var\"",
    "\"Set\"",
    "\"Add+\"",
    "\"Less-\"",
    "\"Begin\"",
    "\"End\"",
    "\"Proc\"",
    "\"End-Proc\"",
    "\"place-block\"",
    "\"high-block\"",
    "\"Pos\"",
    "\"put-light\"",
    "\"Keep\"",
    "\"Kend\"",
    "\"Times\"",
    "\"Skip\"",
    "\"For\"",
    "\"FEnd\"",
    "\"When\"",
    "\"Whend\"",
    "\"Then\"",
    "\"PosStart\"",
    "\"Call\"",
    "\"ChangeDir\"",
    "\"Right\"",
    "\"Left\"",
    "\"Back\"",
    "\"Same\"",
    "<INTEGER>",
    "<PROCNAME>",
    "<IDENTIFIER>",
    "\" \"",
    "\"\\r\\n\"",
    "\"\\t\"",
  };

}
